/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package school.learncoding.cleanjava.annotations;

public class Duck {
    public boolean someLibraryMethod() {
        return true;
    }
}
